---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-multi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ng-multi
  template:
    metadata:
      labels:
        app: ng-multi
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      - image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent
        name: network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "10443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 10443
          name: https-port
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "400m"
