$lighthouse_name = "lighthouse-01"
$lighthouse_ip = "192.168.56.20"
$box = "centos7"
$ssh_public_key_path = "~/.ssh/id_rsa.pub"

Vagrant.configure("2") do |config|
  config.vm.define $lighthouse_name do |config|
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "4096"
    end
    config.vm.box = $box
    config.vm.hostname = $lighthouse_name
    config.vm.network "private_network", ip: $lighthouse_ip
    config.vm.provision 'file', 
        source: $ssh_public_key_path, 
        destination: '~/.ssh/authorized_keys'
  end
end