{
 "title": "App",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Security requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "http_request_total",
     "legendFormat": "{{job}}, {{status}}, {{method}}"
    }
   ]
  },
  {
   "title": "Upload requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "http_requests_total",
     "legendFormat": "{{job}}, {{status}}, {{method}}"
    }
   ]
  },
  {
   "title": "Minio files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "minio_cluster_usage_object_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}