---
apiVersion: v1
kind: Service
metadata:
  name: ng-multi-svc
spec:
  ports:
    - name: web
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: tool
      protocol: TCP
      port: 9002
      targetPort: 8080
  selector:
    app: ng-multi