---
- name: Install kubeadm
  hosts: all
  become: true
  remote_user: ubuntu

  tasks:
    - name: Install dependences
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
          - containerd
        update_cache: true

    - name: Create dir
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download key
      ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add repo
      ansible.builtin.shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install kubelet kubeadm kubectl
      ansible.builtin.apt:
        pkg:
          - kubelet
          - kubeadm
          - kubectl
        update_cache: true

    - name: Turn on forwarding
      ansible.builtin.shell: |
        modprobe br_netfilter
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
        echo "net.bridge.bridge-nf-call-iptables=1" >> /etc/syslog.conf
        echo "net.bridge.bridge-nf-call-arptables=1" >> /etc/syslog.conf
        echo "net.bridge.bridge-nf-call-ip6tables=1" >> /etc/syslog.conf
        sysctl -p /etc/sysctl.conf
