---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-backend
spec:
  podSelector:
    matchLabels:
      app: backend-app
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend-app
  policyTypes:
    - Ingress
