apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:

      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 80
        env:
        - name: HTTP_PORT
          value: "80"
        volumeMounts:
        - name: volume-2
          mountPath: /input

      volumes:
      - name: volume-2
        persistentVolumeClaim:
          claimName: pvc-2