---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent
        name: network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 443
          name: https-port
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "400m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
    - name: backend
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: backend