- name: Create database
  ansible.builtin.command: "clickhouse-client -q 'create database {{ database_name }};'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc !=82
  changed_when: create_db.rc == 0
- name: Create table
  tags: clickhouse_db
  ansible.builtin.command:
    "clickhouse-client -q 'create table {{ database_name }}.{{ table_name }}
    (appname String, facility String, hostname String, message String, msgid String, procid UInt16, severity String, timestamp DateTime64, version UInt8) Engine=Log;'"
  register: create_table
  failed_when: create_table.rc != 0 and create_table.rc !=57
  changed_when: create_table.rc == 0
