$kuber_name = "kuber"
$kuber_ip = "192.168.56.10"
$box = "bento/ubuntu-20.04"
$ssh_public_key_path = "~/.ssh/id_rsa.pub"

Vagrant.configure("2") do |config|
  config.vm.define $kuber_name do |config|
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = "4"
      vb.memory = "8096"
    end
    config.vm.box = $box
    config.vm.hostname = $kuber_name
    config.vm.network "private_network", ip: $kuber_ip
    config.vm.provision 'file', 
        source: $ssh_public_key_path, 
        destination: '~/.ssh/authorized_keys'
  end
end